package io.healthassistant.bridge

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/**
 * HMAC byte-parity with python-sdk/.../signing.py:sign_request. Golden vectors
 * were generated by running the Python SDK over the exact same (secret, method,
 * path, body, timestamp) — a regression on either side is caught here. See
 * dev/plans/mobile-app-android-2026-08-07.md §6.3.
 */
class SigningParityTest {

    private val secret = "test-secret-16chars!"
    private val ts = 1_234_567_890L

    @Test
    fun normalAscii() {
        val s = Signing.sign(secret, "POST", "/sync", "{\"x\":1}".encodeToByteArray(), ts)
        assertEquals("541f6d368c3727752a410a4c29056939c31f1206aa02386341b5db55a566a461", s.signature)
    }

    @Test
    fun emptyBody() {
        val s = Signing.sign(secret, "POST", "/sync", ByteArray(0), ts)
        assertEquals("93d667aa19214b05ce453a2b22c9eedf803ada9692dc7cdefd573fdb7e045ca5", s.signature)
    }

    @Test
    fun nonAscii() {
        val s = Signing.sign(secret, "POST", "/map", "{\"name\":\"Natrium\"}".encodeToByteArray(), ts)
        assertEquals("07d7331152ce274c6c9041efd171c33a0538b292e29138bdb46a920a6a74abbc", s.signature)
    }

    @Test
    fun getReadPath() {
        val s = Signing.sign(secret, "GET", "/observations/latest", ByteArray(0), ts)
        assertEquals("471ee3690780bb527423f0073f529864f5ca2f37fa5bd439d14200303a52d641", s.signature)
    }
}
