/**
 * Markdown gallery generator.
 *
 * Reads the scene catalog and the PNG files actually present in docs/images/,
 * then emits TWO separate tour documents:
 *
 *   - docs/SCREENSHOTS.md        — desktop tour (primary, linked from README)
 *   - docs/SCREENSHOTS.MOBILE.md — mobile tour, written only when at least one
 *                                  *-mobile.png exists on disk. Linked from
 *                                  the desktop doc; regenerated when mobile
 *                                  PNGs change, deleted when none remain.
 *
 * Each doc is single-column (one screenshot per scene) — cleaner to read than
 * a side-by-side table and renders correctly on narrow viewport renderers.
 *
 * Invoked by capture.mjs automatically after every run; also runnable via
 *   `node tests-e2e/ui-capture/capture.mjs --gallery-only`.
 */
import { writeFile, unlink } from "node:fs/promises";
import { existsSync } from "node:fs";
import { groups } from "./scenes.mjs";

const GENERATED_BANNER = [
  "<!--",
  "  AUTO-GENERATED by frontend/tests-e2e/ui-capture/gallery.mjs.",
  "  Do not edit by hand — run `npm run capture:ui` to regenerate.",
  "  To add a page, add a scene in frontend/tests-e2e/ui-capture/scenes.mjs.",
  "-->",
].join("\n");

// SCREENSHOTS.md lives in docs/, images in docs/images/ → relative "images/<file>"
function relImagePath(file) {
  return `images/${file}`;
}

// Derive the mobile doc path from the primary gallery path. Keeps the runner's
// CLI surface minimal: one --gallery flag, the mobile doc is auto-derived.
function mobileGalleryPath(gallery) {
  return gallery.replace(/\.md$/i, ".mobile.md");
}

function sceneBlock(scene, viewport, outDir) {
  const file = `${scene.name}-${viewport}.png`;
  const has = scene.viewports.includes(viewport) && existsSync(`${outDir}/${file}`);

  const lines = [];
  lines.push(`### ${scene.name}`);
  lines.push("");
  lines.push(`_${scene.caption}_`);
  lines.push("");
  if (has) {
    lines.push(`![${scene.name} ${viewport}](${relImagePath(file)})`);
  } else {
    lines.push(
      `> ⚠️ No ${viewport} screenshot yet for **${scene.name}**. Run \`npm run capture:ui -- --scene ${scene.name} --viewport ${viewport}\`.`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function buildFrontMatter(viewport, siblingDoc, hasSibling) {
  const md = [];
  md.push(GENERATED_BANNER);
  md.push("");
  md.push(viewport === "desktop" ? "# Health Assistant — Visual Tour" : "# Health Assistant — Visual Tour (Mobile)");
  md.push("");
  md.push("Welcome to the visual tour of Health Assistant. These reproducible screenshots showcase the main pages and use cases of the application, generated against a deterministic seeded clinical dataset.");
  md.push("");
  if (viewport === "desktop") {
    if (hasSibling) {
      md.push(`> Mobile views: [${siblingDoc}](${siblingDoc})`);
    } else {
      md.push("> Mobile views: not captured this run — pass `--viewport mobile` to the capture script to generate.");
    }
  } else {
    md.push("> Mobile-only companion to the desktop tour. See [the primary tour](./SCREENSHOTS.md).");
  }
  md.push("");
  return md;
}


/**
 * Generate (or remove, when no PNGs are on disk) the per-viewport gallery doc.
 * Returns the path written, or null if the doc was deleted because no PNGs exist.
 */
async function writeViewportGallery(scenes, { out, galleryPath, viewport, siblingDoc, hasSibling }) {
  const anyPresent = scenes.some(
    (s) => s.viewports.includes(viewport) && existsSync(`${out}/${s.name}-${viewport}.png`),
  );

  if (!anyPresent) {
    // No fresh captures for this viewport → drop a stale doc so docs/ stays in
    // sync with what's actually on disk.
    if (existsSync(galleryPath)) {
      await unlink(galleryPath).catch(() => {});
      console.log(`No ${viewport} PNGs found — removed stale ${galleryPath}`);
    }
    return null;
  }

  const md = [
    ...buildFrontMatter(viewport, siblingDoc, hasSibling),
  ];
  for (const group of groups) {
    const inGroup = scenes.filter((s) => s.group === group);
    if (inGroup.length === 0) continue;
    md.push(`## ${group}`);
    md.push("");
    for (const s of inGroup) md.push(sceneBlock(s, viewport, out));
  }

  await writeFile(galleryPath, md.join("\n"), "utf8");
  return galleryPath;
}

export async function generateGallery(scenes, opts) {
  const { out, gallery /* , files: _files — kept for parity with the caller */ } = opts;
  const mobileGallery = mobileGalleryPath(gallery);

  // Desktop is the primary doc; mobile companion is generated only if its
  // PNGs are on disk. We need to know the mobile state first so the desktop
  // doc's "mobile views" footer line is accurate.
  const mobilePresent = scenes.some(
    (s) => s.viewports.includes("mobile") && existsSync(`${out}/${s.name}-mobile.png`),
  );

  const writtenDesktop = await writeViewportGallery(scenes, {
    out,
    galleryPath: gallery,
    viewport: "desktop",
    siblingDoc: "SCREENSHOTS.MOBILE.md",
    hasSibling: mobilePresent,
  });
  const writtenMobile = mobilePresent
    ? await writeViewportGallery(scenes, {
        out,
        galleryPath: mobileGallery,
        viewport: "mobile",
        siblingDoc: "screenshots.md",
        hasSibling: writtenDesktop !== null,
      })
    : await (async () => {
        // No mobile PNGs — drop a stale mobile doc so docs/ stays in sync
        // with what's actually on disk (e.g. after a --viewport desktop run).
        if (existsSync(mobileGallery)) {
          await unlink(mobileGallery).catch(() => {});
          console.log(`No mobile PNGs found — removed stale ${mobileGallery}`);
        }
        return null;
      })();

  return { desktop: writtenDesktop, mobile: writtenMobile };
}