"""add_notifications

Revision ID: 07c550bbe0c8
Revises: 2983797a70d0
Create Date: 2026-03-24 11:31:37.048976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07c550bbe0c8'
down_revision: Union[str, Sequence[str], None] = '2983797a70d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_triggers',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.Enum('TIME', 'RECURRING', 'EVENT', 'THRESHOLD', name='triggertype'), nullable=False),
    sa.Column('notification_type', sa.Enum('MEDICATION_REMINDER', 'EXAMINATION_REMINDER', 'BIOMARKER_ALERT', 'CALENDAR_EVENT', 'AI_SUGGESTION', 'SYSTEM_UPDATE', 'CUSTOM', name='notificationtype'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_trigger', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['fhir_patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_triggers', schema=None) as batch_op:
        batch_op.create_index('idx_trigger_next_run', ['next_trigger', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_triggers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_triggers_next_trigger'), ['next_trigger'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_triggers_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_triggers_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_triggers_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_triggers_updated_at'), ['updated_at'], unique=False)

    op.create_table('notification_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_subscriptions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_subscriptions_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('trigger_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('MEDICATION_REMINDER', 'EXAMINATION_REMINDER', 'BIOMARKER_ALERT', 'CALENDAR_EVENT', 'AI_SUGGESTION', 'SYSTEM_UPDATE', 'CUSTOM', name='notificationtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'READ', 'DISMISSED', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'PUSH', 'EMAIL', 'SMS', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fhir_resource_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['fhir_patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['notification_triggers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_patient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index('idx_notification_patient_status')

    op.drop_table('notifications')
    with op.batch_alter_table('notification_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_subscriptions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notification_subscriptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notification_subscriptions_created_at'))

    op.drop_table('notification_subscriptions')
    with op.batch_alter_table('notification_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_triggers_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notification_triggers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notification_triggers_reference_id'))
        batch_op.drop_index(batch_op.f('ix_notification_triggers_patient_id'))
        batch_op.drop_index(batch_op.f('ix_notification_triggers_next_trigger'))
        batch_op.drop_index(batch_op.f('ix_notification_triggers_created_at'))
        batch_op.drop_index('idx_trigger_next_run')

    op.drop_table('notification_triggers')
    # ### end Alembic commands ###
