"""add info to biomarker definition

Revision ID: 0ddaf4abfa4c
Revises: cdc9464880c3
Create Date: 2026-03-12 21:36:58.980886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddaf4abfa4c'
down_revision: Union[str, Sequence[str], None] = 'cdc9464880c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomarker_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomarker_definitions', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
