"""add_clinical_events

Revision ID: 120a6d0cb048
Revises: 77acb7ec9e03
Create Date: 2026-03-23 16:52:50.310558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "120a6d0cb048"
down_revision: Union[str, Sequence[str], None] = "77acb7ec9e03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinical_event_types",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column(
            "metadata_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("clinical_event_types", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_clinical_event_types_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_event_types_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_event_types_updated_at"),
            ["updated_at"],
            unique=False,
        )

    op.create_table(
        "clinical_events",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("type_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active", "resolved", "on_hold", "unknown", name="clinicaleventstatus"
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("onset_date", sa.DateTime(), nullable=True),
        sa.Column("resolved_date", sa.DateTime(), nullable=True),
        sa.Column(
            "occurrences", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("code", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["fhir_patients.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["clinical_event_types.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clinical_events", schema=None) as batch_op:
        batch_op.create_index(
            "idx_clinical_event_patient_type", ["patient_id", "type_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_events_onset_date"), ["onset_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_events_patient_id"), ["patient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_events_resolved_date"),
            ["resolved_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_events_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_events_type_id"), ["type_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_events_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "event_examination_links",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("examination_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["clinical_events.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["examination_id"], ["examinations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event_examination_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_examination_links_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_event_examination_links_event_id"),
            ["event_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_event_examination_links_examination_id"),
            ["examination_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_event_examination_links_updated_at"),
            ["updated_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_examination_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_examination_links_updated_at"))
        batch_op.drop_index(batch_op.f("ix_event_examination_links_examination_id"))
        batch_op.drop_index(batch_op.f("ix_event_examination_links_event_id"))
        batch_op.drop_index(batch_op.f("ix_event_examination_links_created_at"))

    op.drop_table("event_examination_links")
    with op.batch_alter_table("clinical_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clinical_events_updated_at"))
        batch_op.drop_index(batch_op.f("ix_clinical_events_type_id"))
        batch_op.drop_index(batch_op.f("ix_clinical_events_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_clinical_events_resolved_date"))
        batch_op.drop_index(batch_op.f("ix_clinical_events_patient_id"))
        batch_op.drop_index(batch_op.f("ix_clinical_events_onset_date"))
        batch_op.drop_index(batch_op.f("ix_clinical_events_created_at"))
        batch_op.drop_index("idx_clinical_event_patient_type")

    op.drop_table("clinical_events")
    with op.batch_alter_table("clinical_event_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clinical_event_types_updated_at"))
        batch_op.drop_index(batch_op.f("ix_clinical_event_types_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_clinical_event_types_created_at"))

    op.drop_table("clinical_event_types")
    # ### end Alembic commands ###
