"""expression index on Observation.subject (E1)

Revision ID: 345e12079058
Revises: 223497128688
Create Date: 2026-06-22 18:47:01.722845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345e12079058'
down_revision: Union[str, Sequence[str], None] = '223497128688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.create_index('ix_fhir_diagnostic_reports_subject_ref', [sa.literal_column("(subject->>'reference')")], unique=False)

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.create_index('ix_fhir_observations_subject_ref', [sa.literal_column("(subject->>'reference')")], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_fhir_observations_subject_ref')

    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_fhir_diagnostic_reports_subject_ref')

    # ### end Alembic commands ###
