"""Add cumulative extraction fields

Revision ID: 34f8b79e8ce2
Revises: a4518e1bc8a1
Create Date: 2026-03-13 01:37:19.517479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "34f8b79e8ce2"
down_revision: Union[str, Sequence[str], None] = "a4518e1bc8a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("include_in_extraction", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE documents SET include_in_extraction = false")
    op.alter_column("documents", "include_in_extraction", nullable=False)

    with op.batch_alter_table("examinations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "diagnoses", postgresql.JSONB(astext_type=sa.Text()), nullable=True
            )
        )
        batch_op.add_column(sa.Column("impressions", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("extraction_status", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("extraction_progress", sa.Integer(), nullable=True)
        )

    with op.batch_alter_table("fhir_medications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("examination_id", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_fhir_medications_examination_id"),
            ["examination_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            None, "examinations", ["examination_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("fhir_observations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("examination_id", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_fhir_observations_examination_id"),
            ["examination_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            None, "examinations", ["examination_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fhir_observations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_fhir_observations_examination_id"))
        batch_op.drop_column("examination_id")

    with op.batch_alter_table("fhir_medications", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_fhir_medications_examination_id"))
        batch_op.drop_column("examination_id")

    with op.batch_alter_table("examinations", schema=None) as batch_op:
        batch_op.drop_column("extraction_progress")
        batch_op.drop_column("extraction_status")
        batch_op.drop_column("impressions")
        batch_op.drop_column("diagnoses")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_column("include_in_extraction")

    # ### end Alembic commands ###
