"""add_user_integrations_table

Revision ID: 41596bb879ff
Revises: 81f6d32b2117
Create Date: 2026-06-11 18:25:40.011176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41596bb879ff'
down_revision: Union[str, Sequence[str], None] = '81f6d32b2117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_integrations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'ERROR', name='integrationstatus'), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(length=1000), nullable=True),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['fhir_patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uix_user_provider')
    )
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_integrations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_integrations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_integrations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_integrations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_integrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_integrations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_integrations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_user_integrations_created_at'))

    op.drop_table('user_integrations')
    # ### end Alembic commands ###
