"""Add instance_name and remove unique constraint from user_integrations

Revision ID: 4224fbd563ce
Revises: 23c8ebbb89d1
Create Date: 2026-06-13 02:14:43.678572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4224fbd563ce'
down_revision: Union[str, Sequence[str], None] = '23c8ebbb89d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_name', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('uix_user_provider'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uix_user_provider'), ['user_id', 'provider'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('instance_name')

    # ### end Alembic commands ###
