"""Add EventAnatomyLink

Revision ID: 4f61f50eb0be
Revises: 9b140c7871b7
Create Date: 2026-06-26 21:08:26.138566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f61f50eb0be'
down_revision: Union[str, Sequence[str], None] = '9b140c7871b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_anatomy_links',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('anatomy_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anatomy_id'], ['anatomy_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['clinical_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_anatomy_links', schema=None) as batch_op:
        batch_op.create_index('idx_event_anatomy_link', ['event_id', 'anatomy_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_anatomy_links_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_anatomy_links_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('body_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_parts_created_at'))
        batch_op.drop_index(batch_op.f('ix_body_parts_slug'))
        batch_op.drop_index(batch_op.f('ix_body_parts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_body_parts_updated_at'))

    op.drop_table('body_parts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_parts',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('snomed_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('body_parts_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('body_parts_pkey'))
    )
    with op.batch_alter_table('body_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_parts_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_parts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_parts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_body_parts_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('event_anatomy_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_anatomy_links_updated_at'))
        batch_op.drop_index(batch_op.f('ix_event_anatomy_links_created_at'))
        batch_op.drop_index('idx_event_anatomy_link')

    op.drop_table('event_anatomy_links')
    # ### end Alembic commands ###
