"""Add organizations and associations

Revision ID: 5722373aff93
Revises: 0d73b62677aa
Create Date: 2026-03-26 00:36:29.582488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5722373aff93'
down_revision: Union[str, Sequence[str], None] = '0d73b62677aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fhir_organizations',
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telecom', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('part_of_id', sa.UUID(), nullable=True),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['part_of_id'], ['fhir_organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fhir_organizations', schema=None) as batch_op:
        batch_op.create_index('idx_organization_tenant_name', ['tenant_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_organizations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('organization_doctors',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['fhir_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'doctor_id')
    )
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_examinations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'fhir_organizations', ['organization_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_examinations_organization_id'))
        batch_op.drop_column('organization_id')

    op.drop_table('organization_doctors')
    with op.batch_alter_table('fhir_organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_organizations_tenant_id'))
        batch_op.drop_index('idx_organization_tenant_name')

    op.drop_table('fhir_organizations')
    # ### end Alembic commands ###
