"""Add source tracking to examinations

Revision ID: 5a72ec0aac2e
Revises: 1a829b7421ae
Create Date: 2026-06-17 01:42:32.970090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a72ec0aac2e'
down_revision: Union[str, Sequence[str], None] = '1a829b7421ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_integration_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_examinations_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_examinations_source_integration_id'), ['source_integration_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_integrations', ['source_integration_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_examinations_source_integration_id'))
        batch_op.drop_index(batch_op.f('ix_examinations_external_id'))
        batch_op.drop_column('external_id')
        batch_op.drop_column('source_integration_id')

    # ### end Alembic commands ###
