"""add user_id to ai config tables

Revision ID: 5b22c66d1503
Revises: d3eea9fddafe
Create Date: 2026-03-24 09:58:23.997087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b22c66d1503'
down_revision: Union[str, Sequence[str], None] = 'd3eea9fddafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True))
        batch_op.create_index('idx_ai_providers_tenant_active', ['tenant_id', 'is_active'], unique=False)
        batch_op.create_index('idx_ai_providers_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_providers_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ai_task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True))
        batch_op.create_index('idx_ai_task_assignments_priority', ['priority'], unique=False)
        batch_op.create_index('idx_ai_task_assignments_tenant_task', ['tenant_id', 'task_type', 'is_active'], unique=False)
        batch_op.create_index('idx_ai_task_assignments_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_task_assignments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('examination_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_examination_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_examination_categories_updated_at'), ['updated_at'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_allergy_intolerances', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('fhir_medications', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('patient_layouts', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('patient_layouts', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('fhir_medications', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('fhir_allergy_intolerances', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('examination_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_examination_categories_updated_at'))
        batch_op.drop_index(batch_op.f('ix_examination_categories_created_at'))

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('ai_task_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_task_assignments_user_id'))
        batch_op.drop_index('idx_ai_task_assignments_user')
        batch_op.drop_index('idx_ai_task_assignments_tenant_task')
        batch_op.drop_index('idx_ai_task_assignments_priority')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_providers_user_id'))
        batch_op.drop_index('idx_ai_providers_user')
        batch_op.drop_index('idx_ai_providers_tenant_active')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
