"""Add Biomarker Engine Models

Revision ID: 60659cdf3e36
Revises: c85747872cb1
Create Date: 2026-03-12 16:02:07.842831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60659cdf3e36'
down_revision: Union[str, Sequence[str], None] = 'c85747872cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomarker_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biomarker_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biomarker_groups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_groups_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_groups_updated_at'), ['updated_at'], unique=False)

    op.create_table('laboratories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('standard_rating', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laboratories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_laboratories_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_laboratories_updated_at'), ['updated_at'], unique=False)

    op.create_table('units',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity_type', sa.Enum('MASS_CONCENTRATION', 'MOLAR_CONCENTRATION', 'NUMBER_CONCENTRATION', 'PERCENTAGE', 'PRESSURE', 'VOLUME', 'MASS', 'TIME', 'RATIO', 'TEMPERATURE', 'OTHER', name='quantitytype'), nullable=False),
    sa.Column('base_unit_id', sa.UUID(), nullable=True),
    sa.Column('conversion_multiplier', sa.Float(), nullable=False),
    sa.Column('dashboard_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['base_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_symbol'), ['symbol'], unique=True)
        batch_op.create_index(batch_op.f('ix_units_updated_at'), ['updated_at'], unique=False)

    op.create_table('biomarker_definitions',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('preferred_unit_id', sa.UUID(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['preferred_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biomarker_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biomarker_definitions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_definitions_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_biomarker_definitions_updated_at'), ['updated_at'], unique=False)

    op.create_table('biomarker_group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('biomarker_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['biomarker_id'], ['biomarker_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['biomarker_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biomarker_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biomarker_group_members_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_group_members_updated_at'), ['updated_at'], unique=False)

    op.create_table('biomarker_relationships',
    sa.Column('source_biomarker_id', sa.UUID(), nullable=False),
    sa.Column('target_biomarker_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_biomarker_id'], ['biomarker_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_biomarker_id'], ['biomarker_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biomarker_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biomarker_relationships_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_relationships_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biomarker_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('lab_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('method', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('raw_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('raw_unit_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('normalized_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('relative_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lab_reference_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_index(batch_op.f('ix_fhir_observations_biomarker_id'), ['biomarker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_observations_lab_id'), ['lab_id'], unique=False)
        batch_op.create_foreign_key(None, 'units', ['raw_unit_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'biomarker_definitions', ['biomarker_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'laboratories', ['lab_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fhir_observations_lab_id'))
        batch_op.drop_index(batch_op.f('ix_fhir_observations_biomarker_id'))
        batch_op.drop_column('lab_reference_range')
        batch_op.drop_column('relative_score')
        batch_op.drop_column('normalized_value')
        batch_op.drop_column('raw_unit_id')
        batch_op.drop_column('raw_value')
        batch_op.drop_column('method')
        batch_op.drop_column('lab_id')
        batch_op.drop_column('biomarker_id')

    with op.batch_alter_table('biomarker_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biomarker_relationships_updated_at'))
        batch_op.drop_index(batch_op.f('ix_biomarker_relationships_created_at'))

    op.drop_table('biomarker_relationships')
    with op.batch_alter_table('biomarker_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biomarker_group_members_updated_at'))
        batch_op.drop_index(batch_op.f('ix_biomarker_group_members_created_at'))

    op.drop_table('biomarker_group_members')
    with op.batch_alter_table('biomarker_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biomarker_definitions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_biomarker_definitions_slug'))
        batch_op.drop_index(batch_op.f('ix_biomarker_definitions_created_at'))

    op.drop_table('biomarker_definitions')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_updated_at'))
        batch_op.drop_index(batch_op.f('ix_units_symbol'))
        batch_op.drop_index(batch_op.f('ix_units_created_at'))

    op.drop_table('units')
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laboratories_updated_at'))
        batch_op.drop_index(batch_op.f('ix_laboratories_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_laboratories_created_at'))

    op.drop_table('laboratories')
    with op.batch_alter_table('biomarker_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biomarker_groups_updated_at'))
        batch_op.drop_index(batch_op.f('ix_biomarker_groups_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_biomarker_groups_created_at'))

    op.drop_table('biomarker_groups')
    # ### end Alembic commands ###
