"""initial_schema

Revision ID: 7f38bb0df1d4
Revises:
Create Date: 2026-03-12 13:53:15.733471

"""

import asyncio
import os
import sys
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7f38bb0df1d4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allergy_catalog",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "food",
                "medication",
                "environment",
                "biologic",
                "other",
                name="allergycategory",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "typical_reactions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("allergy_catalog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_allergy_catalog_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allergy_catalog_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allergy_catalog_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "doctors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("specialty", sa.String(length=255), nullable=True),
        sa.Column("license_number", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doctors_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "fhir_diagnostic_reports",
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("category", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("code", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("subject", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_datetime", sa.DateTime(), nullable=True),
        sa.Column("issued", sa.DateTime(), nullable=True),
        sa.Column("performer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("conclusion", sa.String(), nullable=True),
        sa.Column(
            "conclusion_code", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "presented_form", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fhir_diagnostic_reports", schema=None) as batch_op:
        batch_op.create_index(
            "idx_diagnostic_report_tenant_date",
            ["tenant_id", "effective_datetime"],
            unique=False,
        )
        batch_op.create_index(
            "idx_diagnostic_report_tenant_patient",
            ["tenant_id", "subject"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_diagnostic_reports_tenant_id"),
            ["tenant_id"],
            unique=False,
        )

    op.create_table(
        "fhir_observations",
        sa.Column("document_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("category", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("code", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("subject", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_datetime", sa.DateTime(), nullable=True),
        sa.Column(
            "value_quantity", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("value_string", sa.String(), nullable=True),
        sa.Column(
            "value_codeableConcept",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "reference_range", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("interpretation", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("performer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fhir_observations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_observation_tenant_code", ["tenant_id", "code"], unique=False
        )
        batch_op.create_index(
            "idx_observation_tenant_date",
            ["tenant_id", "effective_datetime"],
            unique=False,
        )
        batch_op.create_index(
            "idx_observation_tenant_patient", ["tenant_id", "subject"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_observations_document_id"),
            ["document_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_observations_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "fhir_patients",
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "OTHER", "UNKNOWN", name="gender"),
            nullable=False,
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("deceased_boolean", sa.Boolean(), nullable=True),
        sa.Column("deceased_datetime", sa.DateTime(), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("telecom", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mrn", sa.String(), nullable=True),
        sa.Column(
            "emergency_contact", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "dashboard_layout", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mrn"),
    )
    with op.batch_alter_table("fhir_patients", schema=None) as batch_op:
        batch_op.create_index(
            "idx_patient_tenant_mrn", ["tenant_id", "mrn"], unique=False
        )
        batch_op.create_index(
            "idx_patient_tenant_name", ["tenant_id", "name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_patients_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "medication_catalog",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("indications", sa.Text(), nullable=True),
        sa.Column(
            "side_effects", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("contraindications", sa.Text(), nullable=True),
        sa.Column("dosage_info", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medication_catalog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_medication_catalog_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_medication_catalog_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_medication_catalog_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wearable_data",
        sa.Column("device_id", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("heart_rate", sa.Float(), nullable=True),
        sa.Column("steps", sa.Float(), nullable=True),
        sa.Column("calories", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("wearable_data", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wearable_data_device_id"), ["device_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wearable_data_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wearable_data_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "alerts",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("last_triggered", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["fhir_patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alerts_patient_id"), ["patient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "examinations",
        sa.Column("patient_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("examination_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("patient_notes", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["fhir_patients.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("examinations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_exam_tenant_patient", ["tenant_id", "patient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_examinations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_examinations_examination_date"),
            ["examination_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_examinations_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_examinations_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "fhir_allergy_intolerances",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "clinical_status",
            sa.Enum("active", "inactive", "resolved", name="allergyclinicalstatus"),
            nullable=False,
        ),
        sa.Column("verification_status", sa.String(length=50), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "food",
                "medication",
                "environment",
                "biologic",
                "other",
                name="allergycategory",
            ),
            nullable=True,
        ),
        sa.Column(
            "criticality",
            sa.Enum("low", "high", "unable_to_assess", name="allergycriticality"),
            nullable=True,
        ),
        sa.Column("code", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("onset_date", sa.DateTime(), nullable=True),
        sa.Column("resolved_date", sa.DateTime(), nullable=True),
        sa.Column("last_occurrence", sa.DateTime(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reactions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["fhir_patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fhir_allergy_intolerances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fhir_allergy_intolerances_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_allergy_intolerances_patient_id"),
            ["patient_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_allergy_intolerances_tenant_id"),
            ["tenant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_allergy_intolerances_updated_at"),
            ["updated_at"],
            unique=False,
        )

    op.create_table(
        "fhir_medications",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "completed",
                "entered_in_error",
                "intended",
                "stopped",
                "on_hold",
                "unknown",
                name="medicationstatus",
            ),
            nullable=False,
        ),
        sa.Column("code", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("dosage", sa.String(length=255), nullable=True),
        sa.Column("frequency", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("subject", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["fhir_patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fhir_medications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fhir_medications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_medications_patient_id"), ["patient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_medications_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fhir_medications_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "MANAGER", "USER", name="role"), nullable=False
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=True),
        sa.Column("examination_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("entities", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["examination_id"], ["examinations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["fhir_patients.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            "idx_doc_tenant_owner", ["tenant_id", "owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_examination_id"), ["examination_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_filename"), ["filename"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "examination_doctors",
        sa.Column("examination_id", sa.UUID(), nullable=False),
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["examination_id"], ["examinations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("examination_id", "doctor_id"),
    )
    op.create_table(
        "patient_layouts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "layout_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "cards_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["fhir_patients.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("patient_layouts", schema=None) as batch_op:
        batch_op.create_index(
            "idx_layout_user_patient", ["user_id", "patient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_patient_layouts_patient_id"), ["patient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_patient_layouts_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_patient_layouts_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_layouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patient_layouts_user_id"))
        batch_op.drop_index(batch_op.f("ix_patient_layouts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_patient_layouts_patient_id"))
        batch_op.drop_index("idx_layout_user_patient")

    op.drop_table("patient_layouts")
    op.drop_table("examination_doctors")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_updated_at"))
        batch_op.drop_index(batch_op.f("ix_documents_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_documents_status"))
        batch_op.drop_index(batch_op.f("ix_documents_owner_id"))
        batch_op.drop_index(batch_op.f("ix_documents_filename"))
        batch_op.drop_index(batch_op.f("ix_documents_examination_id"))
        batch_op.drop_index(batch_op.f("ix_documents_created_at"))
        batch_op.drop_index("idx_doc_tenant_owner")

    op.drop_table("documents")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("fhir_medications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fhir_medications_updated_at"))
        batch_op.drop_index(batch_op.f("ix_fhir_medications_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_fhir_medications_patient_id"))
        batch_op.drop_index(batch_op.f("ix_fhir_medications_created_at"))

    op.drop_table("fhir_medications")
    with op.batch_alter_table("fhir_allergy_intolerances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fhir_allergy_intolerances_updated_at"))
        batch_op.drop_index(batch_op.f("ix_fhir_allergy_intolerances_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_fhir_allergy_intolerances_patient_id"))
        batch_op.drop_index(batch_op.f("ix_fhir_allergy_intolerances_created_at"))

    op.drop_table("fhir_allergy_intolerances")
    with op.batch_alter_table("examinations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_examinations_updated_at"))
        batch_op.drop_index(batch_op.f("ix_examinations_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_examinations_examination_date"))
        batch_op.drop_index(batch_op.f("ix_examinations_created_at"))
        batch_op.drop_index("idx_exam_tenant_patient")

    op.drop_table("examinations")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_patient_id"))

    op.drop_table("alerts")
    with op.batch_alter_table("wearable_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wearable_data_timestamp"))
        batch_op.drop_index(batch_op.f("ix_wearable_data_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_wearable_data_device_id"))

    op.drop_table("wearable_data")
    op.drop_table("tenants")
    with op.batch_alter_table("medication_catalog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medication_catalog_updated_at"))
        batch_op.drop_index(batch_op.f("ix_medication_catalog_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_medication_catalog_created_at"))

    op.drop_table("medication_catalog")
    with op.batch_alter_table("fhir_patients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fhir_patients_tenant_id"))
        batch_op.drop_index("idx_patient_tenant_name")
        batch_op.drop_index("idx_patient_tenant_mrn")

    op.drop_table("fhir_patients")
    with op.batch_alter_table("fhir_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fhir_observations_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_fhir_observations_document_id"))
        batch_op.drop_index("idx_observation_tenant_patient")
        batch_op.drop_index("idx_observation_tenant_date")
        batch_op.drop_index("idx_observation_tenant_code")

    op.drop_table("fhir_observations")
    with op.batch_alter_table("fhir_diagnostic_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fhir_diagnostic_reports_tenant_id"))
        batch_op.drop_index("idx_diagnostic_report_tenant_patient")
        batch_op.drop_index("idx_diagnostic_report_tenant_date")

    op.drop_table("fhir_diagnostic_reports")
    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctors_tenant_id"))

    op.drop_table("doctors")
    with op.batch_alter_table("allergy_catalog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allergy_catalog_updated_at"))
        batch_op.drop_index(batch_op.f("ix_allergy_catalog_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_allergy_catalog_created_at"))

    op.drop_table("allergy_catalog")
    # ### end Alembic commands ###
