"""Add system and user integrations

Revision ID: 7f5219d84575
Revises: 41596bb879ff
Create Date: 2026-06-11 19:59:47.268455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f5219d84575'
down_revision: Union[str, Sequence[str], None] = '41596bb879ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_integrations',
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('global_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('access_token',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('user_config')

    op.drop_table('system_integrations')
    # ### end Alembic commands ###
