"""add missing performance indexes (E3-E7)

Revision ID: 82fe70921bb0
Revises: 9c3f090d5238
Create Date: 2026-06-22 19:02:59.078735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fe70921bb0'
down_revision: Union[str, Sequence[str], None] = '9c3f090d5238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomarker_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biomarker_group_members_biomarker_id'), ['biomarker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_group_members_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('biomarker_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biomarker_relationships_source_biomarker_id'), ['source_biomarker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_relationships_target_biomarker_id'), ['target_biomarker_id'], unique=False)

    with op.batch_alter_table('fhir_communications', schema=None) as batch_op:
        batch_op.create_index('ix_fhir_communications_sent', ['sent'], unique=False)

    with op.batch_alter_table('fhir_medications', schema=None) as batch_op:
        batch_op.create_index('ix_fhir_medications_start_date', ['start_date'], unique=False)

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.create_index('ix_fhir_patients_birth_date', ['birth_date'], unique=False)

    with op.batch_alter_table('telemetry_data', schema=None) as batch_op:
        batch_op.create_index('ix_telemetry_data_tenant_timestamp', ['tenant_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_data', schema=None) as batch_op:
        batch_op.drop_index('ix_telemetry_data_tenant_timestamp')

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.drop_index('ix_fhir_patients_birth_date')

    with op.batch_alter_table('fhir_medications', schema=None) as batch_op:
        batch_op.drop_index('ix_fhir_medications_start_date')

    with op.batch_alter_table('fhir_communications', schema=None) as batch_op:
        batch_op.drop_index('ix_fhir_communications_sent')

    with op.batch_alter_table('biomarker_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biomarker_relationships_target_biomarker_id'))
        batch_op.drop_index(batch_op.f('ix_biomarker_relationships_source_biomarker_id'))

    with op.batch_alter_table('biomarker_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biomarker_group_members_group_id'))
        batch_op.drop_index(batch_op.f('ix_biomarker_group_members_biomarker_id'))

    # ### end Alembic commands ###
