"""Add body_parts table

Revision ID: 83bfeb9741cc
Revises: 490b335111b8
Create Date: 2026-03-26 16:52:23.466002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bfeb9741cc'
down_revision: Union[str, Sequence[str], None] = '490b335111b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_parts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('snomed_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_parts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_parts_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_parts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_parts_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_parts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_body_parts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_body_parts_slug'))
        batch_op.drop_index(batch_op.f('ix_body_parts_created_at'))

    op.drop_table('body_parts')
    # ### end Alembic commands ###
