"""add_biomarker_event_correlations_and_links

Revision ID: 9574b2b207f7
Revises: 44a5f0622b1f
Create Date: 2026-06-09 15:14:56.658137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9574b2b207f7'
down_revision: Union[str, Sequence[str], None] = '44a5f0622b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomarker_event_correlations',
    sa.Column('biomarker_id', sa.UUID(), nullable=False),
    sa.Column('event_type_id', sa.UUID(), nullable=False),
    sa.Column('correlation_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['biomarker_id'], ['biomarker_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_type_id'], ['clinical_event_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biomarker_event_correlations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biomarker_event_correlations_biomarker_id'), ['biomarker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_event_correlations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_event_correlations_event_type_id'), ['event_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_event_correlations_updated_at'), ['updated_at'], unique=False)

    op.create_table('event_observation_links',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['clinical_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['fhir_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_observation_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_observation_links_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_observation_links_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_observation_links_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_observation_links_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_observation_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_observation_links_updated_at'))
        batch_op.drop_index(batch_op.f('ix_event_observation_links_observation_id'))
        batch_op.drop_index(batch_op.f('ix_event_observation_links_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_observation_links_created_at'))

    op.drop_table('event_observation_links')
    with op.batch_alter_table('biomarker_event_correlations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biomarker_event_correlations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_biomarker_event_correlations_event_type_id'))
        batch_op.drop_index(batch_op.f('ix_biomarker_event_correlations_created_at'))
        batch_op.drop_index(batch_op.f('ix_biomarker_event_correlations_biomarker_id'))

    op.drop_table('biomarker_event_correlations')
    # ### end Alembic commands ###
