"""Add Anatomy Graph models

Revision ID: 9b140c7871b7
Revises: a1b2c3d4e5f6
Create Date: 2026-06-26 21:05:17.647091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b140c7871b7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anatomy_structures',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('SYSTEM', 'REGION', 'ORGAN', 'ORGAN_PART', 'TISSUE', 'CELL', 'SUBSTANCE', 'JOINT', 'OTHER', name='anatomycategory'), nullable=False),
    sa.Column('standard_system', postgresql.ENUM('LOINC', 'SNOMED', 'CUSTOM', name='codingsystem', create_type=False), nullable=True),
    sa.Column('standard_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anatomy_structures', schema=None) as batch_op:
        batch_op.create_index('idx_anatomy_tenant_slug', ['tenant_id', 'slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_anatomy_structures_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_anatomy_structures_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_anatomy_structures_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anatomy_structures_updated_at'), ['updated_at'], unique=False)

    op.create_table('anatomy_relations',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('PART_OF', 'BRANCH_OF', 'DRAINS_INTO', 'ARTICULATES_WITH', 'INNERVATED_BY', 'SUPPLIED_BY', 'CONTINUOUS_WITH', name='anatomyrelationtype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['anatomy_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['anatomy_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anatomy_relations', schema=None) as batch_op:
        batch_op.create_index('idx_anatomy_relation_unique', ['source_id', 'target_id', 'relation_type'], unique=True)
        batch_op.create_index(batch_op.f('ix_anatomy_relations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_anatomy_relations_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anatomy_relations_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anatomy_relations_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('anatomy_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anatomy_relations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_anatomy_relations_target_id'))
        batch_op.drop_index(batch_op.f('ix_anatomy_relations_source_id'))
        batch_op.drop_index(batch_op.f('ix_anatomy_relations_created_at'))
        batch_op.drop_index('idx_anatomy_relation_unique')

    op.drop_table('anatomy_relations')
    with op.batch_alter_table('anatomy_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anatomy_structures_updated_at'))
        batch_op.drop_index(batch_op.f('ix_anatomy_structures_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_anatomy_structures_slug'))
        batch_op.drop_index(batch_op.f('ix_anatomy_structures_created_at'))
        batch_op.drop_index('idx_anatomy_tenant_slug')

    op.drop_table('anatomy_structures')
    # ### end Alembic commands ###
