"""add ranges to biomarker definition

Revision ID: a4518e1bc8a1
Revises: 0ddaf4abfa4c
Create Date: 2026-03-13 00:35:47.709402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4518e1bc8a1'
down_revision: Union[str, Sequence[str], None] = '0ddaf4abfa4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomarker_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_range_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reference_range_max', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomarker_definitions', schema=None) as batch_op:
        batch_op.drop_column('reference_range_max')
        batch_op.drop_column('reference_range_min')

    # ### end Alembic commands ###
