"""Add is_debug_enabled to user_integrations

Revision ID: bafb4c7b31bc
Revises: 2a022ad62db3
Create Date: 2026-06-13 02:40:28.098747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafb4c7b31bc'
down_revision: Union[str, Sequence[str], None] = '2a022ad62db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_debug_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.drop_column('is_debug_enabled')

    # ### end Alembic commands ###
