"""add tenant_id foreign keys (D8)

Revision ID: ca8c6c3350e6
Revises: 0001
Create Date: 2026-06-22 18:35:25.169640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8c6c3350e6'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.create_foreign_key('ai_providers_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ai_task_assignments', schema=None) as batch_op:
        batch_op.create_foreign_key('ai_task_assignments_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_foreign_key('alerts_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('allergy_catalog', schema=None) as batch_op:
        batch_op.create_foreign_key('allergy_catalog_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('audit_logs_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('body_parts', schema=None) as batch_op:
        batch_op.create_foreign_key('body_parts_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key('chat_sessions_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.create_foreign_key('clinical_events_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_foreign_key('doctors_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.create_foreign_key('export_jobs_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_allergy_intolerances', schema=None) as batch_op:
        batch_op.create_foreign_key('fhir_allergy_intolerances_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_communications', schema=None) as batch_op:
        batch_op.create_foreign_key('fhir_communications_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_devices', schema=None) as batch_op:
        batch_op.create_foreign_key('fhir_devices_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.create_foreign_key('fhir_diagnostic_reports_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_medications', schema=None) as batch_op:
        batch_op.create_foreign_key('fhir_medications_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.create_foreign_key('fhir_observations_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_organizations', schema=None) as batch_op:
        batch_op.create_foreign_key('fhir_organizations_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.create_foreign_key('fhir_patients_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fhir_provenance', schema=None) as batch_op:
        batch_op.create_foreign_key('fhir_provenance_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_foreign_key('import_jobs_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('integration_debug_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('integration_debug_logs_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('integration_sync_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('integration_sync_logs_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('medication_catalog', schema=None) as batch_op:
        batch_op.create_foreign_key('medication_catalog_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notification_subscriptions', schema=None) as batch_op:
        batch_op.create_foreign_key('notification_subscriptions_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notification_triggers', schema=None) as batch_op:
        batch_op.create_foreign_key('notification_triggers_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key('notifications_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('patient_layouts', schema=None) as batch_op:
        batch_op.create_foreign_key('patient_layouts_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('task_logs_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.create_foreign_key('user_integrations_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.drop_constraint('ai_providers_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.drop_constraint('task_logs_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('patient_layouts', schema=None) as batch_op:
        batch_op.drop_constraint('patient_layouts_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('notification_triggers', schema=None) as batch_op:
        batch_op.drop_constraint('notification_triggers_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('notification_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('notification_subscriptions_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('medication_catalog', schema=None) as batch_op:
        batch_op.drop_constraint('medication_catalog_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('integration_sync_logs', schema=None) as batch_op:
        batch_op.drop_constraint('integration_sync_logs_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('integration_debug_logs', schema=None) as batch_op:
        batch_op.drop_constraint('integration_debug_logs_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('import_jobs_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('fhir_provenance', schema=None) as batch_op:
        batch_op.drop_constraint('fhir_provenance_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.drop_constraint('fhir_patients_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('fhir_organizations', schema=None) as batch_op:
        batch_op.drop_constraint('fhir_organizations_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.drop_constraint('fhir_observations_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('fhir_medications', schema=None) as batch_op:
        batch_op.drop_constraint('fhir_medications_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.drop_constraint('fhir_diagnostic_reports_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('fhir_devices', schema=None) as batch_op:
        batch_op.drop_constraint('fhir_devices_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('fhir_communications', schema=None) as batch_op:
        batch_op.drop_constraint('fhir_communications_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('fhir_allergy_intolerances', schema=None) as batch_op:
        batch_op.drop_constraint('fhir_allergy_intolerances_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('export_jobs_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint('doctors_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_events_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('chat_sessions_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('body_parts', schema=None) as batch_op:
        batch_op.drop_constraint('body_parts_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('audit_logs_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('allergy_catalog', schema=None) as batch_op:
        batch_op.drop_constraint('allergy_catalog_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint('alerts_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('ai_task_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('ai_task_assignments_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_constraint('ai_providers_tenant_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###
