"""Make tenant_id nullable for global groups and labs

Revision ID: cdc9464880c3
Revises: 60659cdf3e36
Create Date: 2026-03-12 16:03:02.923840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc9464880c3'
down_revision: Union[str, Sequence[str], None] = '60659cdf3e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomarker_groups', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_biomarker_groups_tenant_id'))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_laboratories_tenant_id'))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_laboratories_tenant_id'), ['tenant_id'], unique=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('biomarker_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_biomarker_groups_tenant_id'), ['tenant_id'], unique=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
