"""add_clinical_event_categories

Revision ID: d3eea9fddafe
Revises: 44e82b28f40b
Create Date: 2026-03-24 01:46:15.167491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d3eea9fddafe"
down_revision: Union[str, Sequence[str], None] = "44e82b28f40b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinical_event_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("clinical_event_categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_clinical_event_categories_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_event_categories_tenant_id"),
            ["tenant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_clinical_event_categories_updated_at"),
            ["updated_at"],
            unique=False,
        )

    with op.batch_alter_table("clinical_event_types", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_clinical_event_types_category_id"),
            ["category_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            None,
            "clinical_event_categories",
            ["category_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clinical_event_types", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_clinical_event_types_category_id"))
        batch_op.drop_column("category_id")

    with op.batch_alter_table("clinical_event_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clinical_event_categories_updated_at"))
        batch_op.drop_index(batch_op.f("ix_clinical_event_categories_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_clinical_event_categories_created_at"))

    op.drop_table("clinical_event_categories")
    # ### end Alembic commands ###
