#!/usr/bin/env python3
import os
import sys
import secrets
import base64
from datetime import datetime

print("Setting up Health Assistant environment...")

if os.path.exists(".env"):
    print("⚠️  .env file already exists. Skipping auto-generation to prevent overwriting your existing configuration.")
    print("If you want to regenerate, please delete or rename your current .env file and run this script again.")
    sys.exit(0)

if not os.path.exists("docker/.env.example"):
    print("❌ Error: docker/.env.example not found. Please run this script from the root of the repository.")
    sys.exit(1)

# Generate secure keys
secret_key = secrets.token_urlsafe(48)
postgres_password = secrets.token_urlsafe(24)
flower_password = secrets.token_urlsafe(24)

# Generate a valid Fernet key (32 bytes, base64url encoded)
fernet_key_bytes = os.urandom(32)
integration_secret_key = base64.urlsafe_b64encode(fernet_key_bytes).decode('utf-8')

print("Copying docker/.env.example to .env and injecting secure keys...")

try:
    with open("docker/.env.example", "r") as example_file:
        lines = example_file.readlines()
        
    with open(".env", "w") as env_file:
        env_file.write(f"# Auto-generated by scripts/setup_env.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        
        for line in lines:
            if line.startswith("SECRET_KEY="):
                env_file.write(f"SECRET_KEY={secret_key}\n")
            elif line.startswith("POSTGRES_PASSWORD="):
                env_file.write(f"POSTGRES_PASSWORD={postgres_password}\n")
            elif line.startswith("FLOWER_PASSWORD="):
                env_file.write(f"FLOWER_PASSWORD={flower_password}\n")
            elif line.startswith("INTEGRATION_SECRET_KEY="):
                env_file.write(f"INTEGRATION_SECRET_KEY={integration_secret_key}\n")
            else:
                env_file.write(line)

    print("✅ Environment configured successfully!")
    print("✨ Secure keys have been automatically generated for:")
    print("   - SECRET_KEY")
    print("   - INTEGRATION_SECRET_KEY")
    print("   - POSTGRES_PASSWORD")
    print("   - FLOWER_PASSWORD")
    print("\nYou can now run 'docker compose -f docker/docker-compose.yml up -d' to start the application.")

except Exception as e:
    print(f"❌ Error during setup: {e}")
    sys.exit(1)
