"""Per-purpose key material (identity-auth §8) — the HA key ring.

H4 (plan 16) key separation. Every token mint/verify resolves its key
through :func:`key_for`, and every at-rest cipher through the DATA_KEY
family (:func:`data_key_family`) — never through ``settings`` directly,
so this module is the single resolution point for the family.

Kind → key map (§8 names exactly three purposes; health mints five JWT
kinds — identity-auth H1):

==================  ==============================================
kind                key
==================  ==============================================
session             ``HA_SESSION_KEY`` — session family
api                 ``HA_SESSION_KEY`` — product kind, session family
invite              ``HA_SESSION_KEY`` — product kind, session family
download            ``HA_SESSION_KEY`` — product kind, session family
mfa_challenge       ``HA_SESSION_KEY`` — product kind, session family
refresh             ``HA_REFRESH_KEY`` — refresh family, refresh only
(at-rest secrets)   ``HA_DATA_KEY`` — Fernet; **never signs a JWT**
==================  ==============================================

Mapping choice for the product kinds: §8 separates *session* from
*refresh* (a stolen/long-lived refresh credential must never be usable
as a session credential and vice versa) and *signing* from *data* (a
JWT HMAC key must never decrypt at-rest ciphertext). api / invite /
download tokens are short-lived, first-party-minted credentials on the
same authority as session tokens, so they ride the session family; the
hard §8 lines are all enforced — refresh shares key material with
nothing, and the DATA_KEY family signs nothing.

Verification is family-locked (:func:`verify_access_token` /
``decode_refresh_token`` in ``app.core.security`` decode under exactly
one key), so cross-family tokens fail: a session token signed by the
refresh key — or by the DATA_KEY — does not verify as a session token.

Resolution order (per key; **no key is derived from another**):

1. **env** — ``HA_SESSION_KEY`` / ``HA_REFRESH_KEY`` / ``HA_DATA_KEY``
   via ``Settings`` (OS env or the deployment ``.env``). A partial
   signing pin fails closed (session without refresh or vice versa).
2. **dev/test only** — a per-process ephemeral secret (32 random bytes,
   generated by the config boot guard). This matches the pre-H4 dev
   fallbacks for both the retired ``SECRET_KEY`` and the integration
   Fernet key: logins do not survive a restart. Health is a server
   product (§4.4) and has no desktop data dir, so career's persisted
   0600 ``auth_keys.json`` pattern does not apply — dev persistence,
   when wanted, is simply pinning the env vars.

Server deployments (non-dev ``APP_ENV``) MUST pin all three keys via
env: the config boot guards refuse missing/weak/placeholder/cross-purpose
values (identity-auth §8 "server = env with weak-secret boot guard").
"""

from __future__ import annotations

from app.core.config import settings

# Every JWT kind health mints (H1 contract constants — see
# app.core.security). Kept literal-by-name to avoid a circular import.
SIGNING_KINDS = ("session", "refresh", "api", "invite", "download", "mfa_challenge")

# Kinds signing under the session family (§8 has one session key).
SESSION_FAMILY_KINDS = ("session", "api", "invite", "download", "mfa_challenge")

# The refresh family is refresh-only by construction.
REFRESH_KIND = "refresh"


def key_for(kind: str) -> str:
    """Signing/verification key for one token kind (identity-auth §8).

    ``session``/``api``/``invite``/``download`` → ``HA_SESSION_KEY``;
    ``refresh`` → ``HA_REFRESH_KEY``. Raises ``ValueError`` for any
    other kind so a typo can never mint under an unintended key.
    """
    if kind in SESSION_FAMILY_KINDS:
        key = settings.HA_SESSION_KEY
    elif kind == REFRESH_KIND:
        key = settings.HA_REFRESH_KEY
    else:
        raise ValueError(f"unknown token kind {kind!r}")
    if not key:
        raise ValueError(f"HA key for token kind {kind!r} is not configured")
    return key


def verification_keys() -> tuple[str, ...]:
    """Every signing key a generic decode may try (peek paths, docs).

    Kind-specific verification never uses this — it locks to one key.
    Deduplicated in case a (forbidden) shared value slips in.
    """
    return tuple(
        key for key in dict.fromkeys((settings.HA_SESSION_KEY, settings.HA_REFRESH_KEY)) if key
    )


def data_key_family() -> tuple[str, ...]:
    """The Fernet at-rest ring: primary first, then decrypt-only priors.

    ``HA_DATA_KEY`` is the
    primary — the only key that ever *encrypts*.
    ``HA_DATA_KEY_PREVIOUS`` (env alias
    ``HA_DATA_KEY_PREVIOUS``, comma-separated) holds prior
    keys tried on *decrypt* only, so ciphertext sealed before a
    rotation keeps working. Never signs a JWT.
    """
    primary = (settings.HA_DATA_KEY or "").strip()
    if not primary:
        # No primary configured — an empty family; callers fail closed
        # (the config boot guard guarantees this never happens outside
        # a monkeypatched test).
        return ()
    previous = [k.strip() for k in (settings.HA_DATA_KEY_PREVIOUS or "").split(",") if k.strip()]
    return tuple(dict.fromkeys([primary, *previous]))
