"""Add IntegrationDebugLog

Revision ID: 2a022ad62db3
Revises: 4224fbd563ce
Create Date: 2026-06-13 02:28:45.550353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a022ad62db3'
down_revision: Union[str, Sequence[str], None] = '4224fbd563ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_debug_logs',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['user_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_debug_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_debug_logs_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_debug_logs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_debug_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_debug_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_integration_debug_logs_integration_id'))

    op.drop_table('integration_debug_logs')
    # ### end Alembic commands ###
