"""Add org_type to organizations and user_id to doctor/patient

Revision ID: 2d4a87441382
Revises: 83bfeb9741cc
Create Date: 2026-06-09 10:36:05.286808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4a87441382'
down_revision: Union[str, Sequence[str], None] = '83bfeb9741cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create Enum type manually for PostgreSQL
    sa.Enum('HOUSEHOLD', 'CLINIC', 'DEPARTMENT', 'PROVIDER_GROUP', 'HOSPITAL', 'OTHER', name='organizationtype').create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_doctors_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fhir_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_type', sa.Enum('HOUSEHOLD', 'CLINIC', 'DEPARTMENT', 'PROVIDER_GROUP', 'HOSPITAL', 'OTHER', name='organizationtype'), nullable=True))
    
    # Fill existing rows with HOUSEHOLD
    op.execute("UPDATE fhir_organizations SET org_type = 'HOUSEHOLD'")
    
    # Now make it non-nullable
    with op.batch_alter_table('fhir_organizations', schema=None) as batch_op:
        batch_op.alter_column('org_type', nullable=False)
        batch_op.create_index(batch_op.f('ix_fhir_organizations_org_type'), ['org_type'], unique=False)

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fhir_patients_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fhir_patients_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('fhir_organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_organizations_org_type'))
        batch_op.drop_column('org_type')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_doctors_user_id'))
        batch_op.drop_column('user_id')

    # Drop Enum type manually
    sa.Enum(name='organizationtype').drop(op.get_bind())

    # ### end Alembic commands ###
