"""Add contact and office info to doctors

Revision ID: 490b335111b8
Revises: 5722373aff93
Create Date: 2026-03-26 16:23:05.672497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '490b335111b8'
down_revision: Union[str, Sequence[str], None] = '5722373aff93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telecom', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('office_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('office_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('office_details')
        batch_op.drop_column('office_number')
        batch_op.drop_column('address')
        batch_op.drop_column('telecom')

    # ### end Alembic commands ###
