"""Add IntegrationSyncLog

Revision ID: 9a31f88a2146
Revises: 7f5219d84575
Create Date: 2026-06-11 23:01:47.342009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a31f88a2146'
down_revision: Union[str, Sequence[str], None] = '7f5219d84575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_sync_logs',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['user_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_sync_logs_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_sync_logs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_sync_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_integration_sync_logs_integration_id'))

    op.drop_table('integration_sync_logs')
    # ### end Alembic commands ###
