"""Add provider transparency fields

Revision ID: b9cb94ab652e
Revises: 86e813516695
Create Date: 2026-06-12 18:12:57.878978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cb94ab652e'
down_revision: Union[str, Sequence[str], None] = '86e813516695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_local', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('company_website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('company_country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_column('company_country')
        batch_op.drop_column('company_website')
        batch_op.drop_column('company_name')
        batch_op.drop_column('is_local')

    # ### end Alembic commands ###
