"""Add task logs table

Revision ID: db3121f74079
Revises: 69f782af2d9a
Create Date: 2026-03-17 12:49:58.539951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db3121f74079"
down_revision: Union[str, Sequence[str], None] = "69f782af2d9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_logs",
        sa.Column("task_name", sa.String(length=100), nullable=False),
        sa.Column("task_id", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_logs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_task_logs_level"), ["level"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_task_logs_resource_id"), ["resource_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_logs_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_logs_task_name"), ["task_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_logs_tenant_id"), ["tenant_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_logs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_task_logs_task_name"))
        batch_op.drop_index(batch_op.f("ix_task_logs_task_id"))
        batch_op.drop_index(batch_op.f("ix_task_logs_resource_id"))
        batch_op.drop_index(batch_op.f("ix_task_logs_level"))
        batch_op.drop_index(batch_op.f("ix_task_logs_created_at"))

    op.drop_table("task_logs")
    # ### end Alembic commands ###
