"""make fhir timestamps timezone aware

Revision ID: e3d6ed664956
Revises: b9c0d36d8496
Create Date: 2026-06-14 06:31:10.337545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3d6ed664956'
down_revision: Union[str, Sequence[str], None] = 'b9c0d36d8496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fhir_allergy_intolerances', schema=None) as batch_op:
        batch_op.alter_column('onset_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('resolved_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('last_occurrence',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.alter_column('effective_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('issued',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.alter_column('effective_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_fhir_observations_raw_unit_id'), ['raw_unit_id'], unique=False)

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.alter_column('deceased_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_system_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_system_settings_created_at'))
        batch_op.alter_column('value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.alter_column('deceased_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_observations_raw_unit_id'))
        batch_op.alter_column('effective_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.alter_column('issued',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('effective_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('fhir_allergy_intolerances', schema=None) as batch_op:
        batch_op.alter_column('last_occurrence',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('resolved_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('onset_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
