"""Add TimestampMixin to FHIR models

Revision ID: eb84ddfb3c4c
Revises: bafb4c7b31bc
Create Date: 2026-06-13 03:15:08.357395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb84ddfb3c4c'
down_revision: Union[str, Sequence[str], None] = 'bafb4c7b31bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.create_index(batch_op.f('ix_fhir_diagnostic_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_diagnostic_reports_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.create_index(batch_op.f('ix_fhir_observations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_observations_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.create_index(batch_op.f('ix_fhir_patients_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_patients_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fhir_patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_patients_updated_at'))
        batch_op.drop_index(batch_op.f('ix_fhir_patients_created_at'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('fhir_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_observations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_fhir_observations_created_at'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('fhir_diagnostic_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_diagnostic_reports_updated_at'))
        batch_op.drop_index(batch_op.f('ix_fhir_diagnostic_reports_created_at'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
