"""add_parent_id_and_is_edited_to_documents

Revision ID: fd359dc0d5ce
Revises: db3121f74079
Create Date: 2026-03-20 13:32:03.581336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd359dc0d5ce"
down_revision: Union[str, Sequence[str], None] = "db3121f74079"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.UUID(), nullable=True))
        batch_op.add_column(
            sa.Column("is_edited", sa.Boolean(), nullable=False, server_default="false")
        )
        batch_op.create_index(
            batch_op.f("ix_documents_parent_id"), ["parent_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_documents_parent_id",
            "documents",
            ["parent_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint("fk_documents_parent_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_documents_parent_id"))
        batch_op.drop_column("is_edited")
        batch_op.drop_column("parent_id")
    # ### end Alembic commands ###
